### PR TITLE
This app is dead, long live Update notifications

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] https://github.com/nextcloud/server/pull/8579

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]

**Comment by ChristophWurst** [comment]
FYI you can [archive](https://help.github.com/articles/archiving-a-github-repository/) this repo now to make it even more obvious.

**Comment by nickvergessen** [comment]
Yeah, will do later, not sure if we need to do something for the 13 to 14 update before

**Comment by nickvergessen** [comment]
For examples see https://github.com/nextcloud/admin_notifications

**Comment by MorrisJobke** [comment]
> For examples see https://github.com/nextcloud/admin_notifications

Maybe also there update the app in the App Store ;)

**Comment by MorrisJobke** [comment]
> Maybe also there update the app in the App Store ;)

But should be fine to do this later shortly before the 14 release.

**Pull request merged**
